# Generated by Django 2.2.6 on 2019-11-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='fn_login',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facebookapp.Login'),
        ),
    ]
