# Generated by Django 2.2.6 on 2019-11-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0002_auto_20191112_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='fn_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebookapp.Login'),
        ),
    ]
