# Generated by Django 2.2.6 on 2019-11-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0003_auto_20191113_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fn_login',
            new_name='loginForm',
        ),
    ]
