# Generated by Django 2.2.6 on 2019-11-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0005_auto_20191118_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profilepics/')),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebookapp.Login')),
            ],
        ),
    ]
